In [ ]:
import tensorflow as tf
import numpy as np

**Создайте трехмерный тензор из массива случайных чисел.**

In [ ]:
# Создаем трехмерный массив
my_array = np.random.randint(0, 10, (3, 2, 3))

# Создаем трехмерный тензор
my_tensor = tf.constant(my_array)
print('Трехмерный тензор: ')
print(my_tensor)

Трехмерный тензор: 
tf.Tensor(
[[[8 5 6]
  [4 7 8]]

 [[3 5 8]
  [7 0 9]]

 [[5 5 3]
  [7 1 0]]], shape=(3, 2, 3), dtype=int64)


**Создайте два тензора: один 2х3, второй 3х4. Умножьте их с помощью функции, затем с помощью оператора матричного умножения сравните результаты.**

In [ ]:
# Первый тензор размерностью 2х3
first_tensor = tf.constant(np.random.randint(0, 10, (2, 3)))
print(first_tensor, '\n')

# Второй тензор размерностью 3х4
second_tensor = tf.constant(np.random.randint(0, 10, (3, 4)))
print(second_tensor)

tf.Tensor(
[[1 6 1]
 [9 4 0]], shape=(2, 3), dtype=int64) 

tf.Tensor(
[[8 3 0 7]
 [8 3 2 2]
 [5 2 5 8]], shape=(3, 4), dtype=int64)


In [ ]:
# Перемножение при помощи функции
print(tf.matmul(first_tensor, second_tensor), '\n')

# Перемножение при помощи оператора матричного умножения
print(first_tensor @ second_tensor)

tf.Tensor(
[[ 61  23  17  27]
 [104  39   8  71]], shape=(2, 4), dtype=int64) 

tf.Tensor(
[[ 61  23  17  27]
 [104  39   8  71]], shape=(2, 4), dtype=int64)


**Создайте ragged тензор. Выведите, на каком устройстве он располагается.**

In [ ]:
# Создаем ragged тензор
ragged_tensor = tf.ragged.constant([[1, 2], [2, 3, 4], [3]])
print(ragged_tensor)

<tf.RaggedTensor [[1, 2], [2, 3, 4], [3]]>


In [ ]:
# Создаем тензор 3х3
valid_tensor = tf.constant([[1, 2, 0], [2, 3, 4], [0, 0, 3]])
print(valid_tensor)

tf.Tensor(
[[1 2 0]
 [2 3 4]
 [0 0 3]], shape=(3, 3), dtype=int32)


In [ ]:
# Проверяем, какие есть устройства
tf.config.experimental.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
# Проверяем, на каком устройстве он располагается
ragged_tensor.values.device.endswith('CPU:0')

False